# Generated by Django 3.0.5 on 2021-05-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210514_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.AddField(
            model_name='tag',
            name='classname',
            field=models.CharField(default='one', max_length=50, verbose_name='Класс, задающий цвет'),
            preserve_default=False,
        ),
    ]
