# Generated by Django 3.0.5 on 2021-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210514_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='badge_class',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='checkbox_class',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='Цвет тега'),
            preserve_default=False,
        ),
    ]
