# Generated by Django 3.0.5 on 2021-05-21 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210521_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='template_id',
            field=models.CharField(default='one', max_length=50, verbose_name='Название для атрибута id в шаблоне'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='data.Recipe', verbose_name='Рецепт'),
        ),
    ]
