# Generated by Django 3.0.5 on 2021-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210526_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='template_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='one', max_length=50, verbose_name='URL-имя'),
            preserve_default=False,
        ),
    ]
